In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import datetime as dt
import seaborn as sns

%matplotlib inline
plt.style.use('tableau-colorblind10')

In [2]:
#look at first file
df = pd.read_csv(filepath_or_buffer="../data/raw/iea-hydrogen-production-projects-database/projects.csv")
display(df.head(10))

,Unnamed: 0,Ref,Project name,Country,Date online,Decomission date,Status,Technology,Technology_details,Technology_electricity,...,Capacity_MWel,Capacity_Nm³ H₂/h,Capacity_kt H2/y,Capacity_t CO₂ captured/y,IEA zero-carbon estimated normalized capacity [Nm³ H₂/hour],References,Latitude,Longitude,Technology_aggregate,LOWE_CF
0,0,NaN,Other projects from confidential sources (post...,NaN,NaN,NaN,Other,NG w CCUS,NaN,NaN,...,NaN,3.535952e+06,2756.769803,NaN,0.000000e+00,NaN,NaN,NaN,Fossil fuels with CCUS,NaN
1,1,NaN,Other projects from confidential sources (post...,NaN,NaN,NaN,Other,Other,Various types,NaN,...,NaN,6.255649e+05,487.715413,NaN,0.000000e+00,NaN,NaN,NaN,Other,NaN
2,2,NaN,Other projects from confidential sources (post...,NaN,NaN,NaN,Other,Other Electrolysis,Various types,NaN,...,17443.883124,3.876418e+06,3022.210898,NaN,3.876418e+06,NaN,NaN,NaN,Electrolysis,NaN
3,3,NaN,Other projects from confidential sources (2000...,NaN,NaN,NaN,Operational,PEM,NaN,NaN,...,6.541400,1.257962e+03,0.980757,NaN,1.257962e+03,NaN,NaN,NaN,Electrolysis,NaN
4,4,NaN,Other projects from confidential sources (2000...,NaN,NaN,NaN,Operational,ALK,NaN,NaN,...,141.760154,3.081742e+04,24.026497,NaN,3.081742e+04,NaN,NaN,NaN,Electrolysis,NaN
5,5,NaN,Non-energy related projects (2000-2024),NaN,NaN,NaN,Operational,ALK & PEM,NaN,NaN,...,78.393800,NaN,NaN,NaN,0.000000e+00,NaN,NaN,NaN,Electrolysis,NaN
6,6,NaN,Non-energy related projects (post-2024),NaN,NaN,NaN,Other,ALK,NaN,NaN,...,46.556344,NaN,NaN,NaN,0.000000e+00,NaN,NaN,NaN,Electrolysis,NaN
7,7,3.0,H2GO Energy Park Oude-Tonge - 1st phase,NLD,2025.0,NaN,FID/Construction,Other Electrolysis,Unknown PtX,Dedicated renewable,...,2.500000,5.555556e+02,0.433133,NaN,5.555556e+02,[503][630][609],51.703313,4.162536,Electrolysis,0.50
8,8,4.0,H2GO Energy Park Oude-Tonge - 2nd phase,NLD,2030.0,NaN,Concept,Other Electrolysis,Unknown PtX,Dedicated renewable,...,23.500000,5.222222e+03,4.071453,NaN,5.222222e+03,[503][630][609],51.703313,4.162536,Electrolysis,0.50
9,9,5.0,"NortH2, phase 1",NLD,2030.0,NaN,Feasibility study,Other Electrolysis,Unknown PtX,Dedicated renewable,...,4000.000000,8.888889e+05,693.013333,NaN,8.888889e+05,[379],53.465208,6.632985,Electrolysis,0.55

In [3]:
#look at second file
df2 = pd.read_csv(filepath_or_buffer="../data/raw/iea-hydrogen-production-projects-database/references.csv")
df2.head(10)

#this file is not neccessary for the data analysis itself

  Number                                          Reference
0      1  Energieinstitut an der Johannes Kepler Univers...
1      2  European Power-to-Gas platform - Power-to-Gas ...
2      3  Bailera et al., 2017. Power to Gas projects re...
3      4  F. Smeets and D. Thomas, 2017, HyBALANCE : sta...
4      5  G. Gahleitner, 2013. Hydrogen from renewable e...
5      6  M. Gotz et al, 2015. Renewable Power-to-Gas: A...
6      7  Master’s Thesis - Vesa Vartiainen, 2016. SCREE...
7      8  Alkaline vs PEM electrolysers: lessons learnt ...
8      9  Global screening of projects and technologies ...
9     10  Energiepark Mainz: Technical and economic anal...

In [4]:
#check df out
print("shape: ", df.shape)
print("---")
print("columns: ", df.columns)
print("---")
display(df.dtypes)
print("----")
display("describe: ", df.describe())
print(print("----"))
print("NaN-Values: ", df.isna().sum())

shape:  (2441, 37)
---
columns:  Index(['Unnamed: 0', 'Ref', 'Project name', 'Country', 'Date online',
       'Decomission date', 'Status', 'Technology', 'Technology_details',
       'Technology_electricity', 'Technology_electricity_details', 'Product',
       'EndUse_Refining', 'EndUse_Ammonia', 'EndUse_Methanol',
       'EndUse_Iron&Steel', 'EndUse_Other Ind', 'EndUse_Mobility',
       'EndUse_Power', 'EndUse_Grid inj.', 'EndUse_CHP',
       'EndUse_Domestic heat', 'EndUse_Biofuels', 'EndUse_Synfuels',
       'EndUse_CH4 grid inj.', 'EndUse_CH4 mobility', 'Announced Size',
       'Capacity_MWel', 'Capacity_Nm³ H₂/h', 'Capacity_kt H2/y',
       'Capacity_t CO₂ captured/y',
       'IEA zero-carbon estimated normalized capacity [Nm³ H₂/hour]',
       'References', 'Latitude', 'Longitude', 'Technology_aggregate',
       'LOWE_CF'],
      dtype='object')
---

Unnamed: 0                                                       int64
Ref                                                            float64
Project name                                                    object
Country                                                         object
Date online                                                    float64
Decomission date                                               float64
Status                                                          object
Technology                                                      object
Technology_details                                              object
Technology_electricity                                          object
Technology_electricity_details                                  object
Product                                                         object
EndUse_Refining                                                float64
EndUse_Ammonia                                                 float64
EndUse_Methanol                                                float64
EndUse_Iron&Steel                                              float64
EndUse_Other Ind                                               float64
EndUse_Mobility                                                float64
EndUse_Power                                                   float64
EndUse_Grid inj.                                               float64
EndUse_CHP                                                     float64
EndUse_Domestic heat                                           float64
EndUse_Biofuels                                                float64
EndUse_Synfuels                                                float64
EndUse_CH4 grid inj.                                           float64
EndUse_CH4 mobility                                            float64
Announced Size                                                  object
Capacity_MWel                                                  float64
Capacity_Nm³ H₂/h                                              float64
Capacity_kt H2/y                                               float64
Capacity_t CO₂ captured/y                                      float64
IEA zero-carbon estimated normalized capacity [Nm³ H₂/hour]    float64
References                                                      object
Latitude                                                       float64
Longitude                                                      float64
Technology_aggregate                                            object
LOWE_CF                                                        float64
dtype: object

----

'describe: '

,Unnamed: 0,Ref,Date online,Decomission date,EndUse_Refining,EndUse_Ammonia,EndUse_Methanol,EndUse_Iron&Steel,EndUse_Other Ind,EndUse_Mobility,...,EndUse_CH4 grid inj.,EndUse_CH4 mobility,Capacity_MWel,Capacity_Nm³ H₂/h,Capacity_kt H2/y,Capacity_t CO₂ captured/y,IEA zero-carbon estimated normalized capacity [Nm³ H₂/hour],Latitude,Longitude,LOWE_CF
count,2441.000000,2434.000000,1879.000000,114.000000,154.0,422.0,168.0,108.0,427.0,696.0,...,75.0,20.0,2024.000000,2.148000e+03,2160.000000,1.020000e+02,2.423000e+03,2434.000000,2434.000000,2433.000000
mean,1220.000000,1745.654478,2024.084619,2016.280702,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,528.988495,1.246207e+05,97.266751,1.524956e+06,1.048537e+05,27.277702,11.867816,0.554353
std,704.800326,876.589046,6.268298,6.889146,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,2084.406713,4.650136e+05,361.604500,2.142721e+06,4.244886e+05,28.784913,61.701600,0.156742
min,0.000000,3.000000,1965.000000,2004.000000,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,0.000000,1.154379e-02,0.000000,1.200000e-01,0.000000e+00,-54.105177,-155.555979,0.300000
25%,610.000000,1013.500000,2023.000000,2013.000000,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,2.000000,5.555556e+02,0.433133,4.700000e+05,1.923077e+02,0.000000,-3.704569,0.500000
50%,1220.000000,1822.500000,2025.000000,2016.000000,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,32.279367,9.615385e+03,7.498269,1.000000e+06,4.681648e+03,38.057223,3.565561,0.550000
75%,1830.000000,2485.750000,2027.000000,2019.000000,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,280.000000,7.289956e+04,57.398100,1.700000e+06,5.769231e+04,51.067839,24.263300,0.570000
max,2440.000000,3160.000000,2043.000000,2063.000000,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,41574.271697,9.238727e+06,7202.881152,1.500000e+07,9.238727e+06,71.105444,178.447084,0.900000

----
None
NaN-Values:  Unnamed: 0                                                        0
Ref                                                               7
Project name                                                      0
Country                                                           7
Date online                                                     562
Decomission date                                               2327
Status                                                            9
Technology                                                        1
Technology_details                                              816
Technology_electricity                                          297
Technology_electricity_details                                 1066
Product                                                          16
EndUse_Refining                                                2287
EndUse_Ammonia                                                 2019
EndUse_Methanol                                                2273
EndUse_Iron&Steel                                              2333
EndUse_Other Ind                                               2014
EndUse_Mobility                                                1745
EndUse_Power                                                   2184
EndUse_Grid inj.                                               2270
EndUse_CHP                                                     2404
EndUse_Domestic heat                                           2397
EndUse_Biofuels                                                2423
EndUse_Synfuels                                                2309
EndUse_CH4 grid inj.                                           2366
EndUse_CH4 mobility                                            2421
Announced Size                                                  219
Capacity_MWel                                                   417
Capacity_Nm³ H₂/h                                               293
Capacity_kt H2/y                                                281
Capacity_t CO₂ captured/y                                      2339
IEA zero-carbon estimated normalized capacity [Nm³ H₂/hour]      18
References                                                      156
Latitude                                                          7
Longitude                                                         7
Technology_aggregate                                              1
LOWE_CF                                                           8
dtype: int64

In [5]:
#delete  unneccessary columns

del df["Unnamed: 0"]
del df["Ref"]

In [6]:
#display(sns.pairplot(df))

In [7]:
#check which countries are listed
df["Country"].unique()

array([nan, 'NLD', 'NOR', 'SWE', 'ESP', 'USA', 'JPN', 'CHE', 'DEU', 'GBR',
       'DNK', 'AUT', 'CHN', 'CAN', 'EST', 'FRA', 'MYS', 'AUS', 'POL',
       'FIN', 'SGP', 'THA', 'ITA', 'CRI', 'CHL', 'BEL', 'IND', 'GRC',
       'ISL', 'TUR', 'ARG', 'IRN', 'NZL', 'PRT', 'LBN', 'MRT', 'PRT\nESP',
       'SAU', 'ROM\nDEU\nAUT', 'POL\nCZE\nSVK\nHUN', 'COK', 'ZAF', 'ARE',
       'OMN', 'URY', 'PRY', 'ESP\nFRA', 'KOR', 'MAR', 'ALB', 'IDN', 'BRB',
       'TTO', 'BGD', 'BRA', 'HUN', 'TWN', 'MEX', 'VNM', 'SVN', 'CZE',
       'SVK', 'DEU\nDNK', 'LTU', 'LVA', 'IRL', 'PER', 'RUS', 'COL', 'KAZ',
       'EGY', 'ZWE', 'NAM', 'KEN', 'BWA', 'PAK', 'COD', 'AGO', 'UKR',
       'BGR', 'LUX', 'ROU', 'LKA', 'NER', 'DJI', 'UZB', 'PAN', 'MNG',
       'DMA', 'JOR', 'MOZ', 'DOM', 'QAT', 'SRB', 'PHL', 'FJI', 'UGA',
       'CYP', 'HRV', 'TUN', 'DZA', 'BHR', 'ISR'], dtype=object)

In [8]:
#have a proper look at the first seven project, which have no information about location
#also use this to have a look at the columns not displayed before, therefore increasing to 10 lines
with pd.option_context('display.max_columns', None):
    print(df.iloc[0:10, :])

#the first seven lines do not contain sufficient information to be counted as reliable source and will therefore be deleted

                                        Project name Country  Date online  \
0  Other projects from confidential sources (post...     NaN          NaN
1  Other projects from confidential sources (post...     NaN          NaN
2  Other projects from confidential sources (post...     NaN          NaN
3  Other projects from confidential sources (2000...     NaN          NaN
4  Other projects from confidential sources (2000...     NaN          NaN
5            Non-energy related projects (2000-2024)     NaN          NaN
6            Non-energy related projects (post-2024)     NaN          NaN
7            H2GO Energy Park Oude-Tonge - 1st phase     NLD       2025.0
8            H2GO Energy Park Oude-Tonge - 2nd phase     NLD       2030.0
9                                    NortH2, phase 1     NLD       2030.0

   Decomission date             Status          Technology Technology_details  \
0               NaN              Other           NG w CCUS                NaN
1               NaN              Other               Other      Various types
2               NaN              Other  Other Electrolysis      Various types
3               NaN        Operational                 PEM                NaN
4               NaN        Operational                 ALK                NaN
5               NaN        Operational           ALK & PEM                NaN
6               NaN              Other                 ALK                NaN
7               NaN   FID/Construction  Other Electrolysis        Unknown PtX
8               NaN            Concept  Other Electrolysis        Unknown PtX
9               NaN  Feasibility study  Other Electrolysis        Unknown PtX

  Technology_electricity Technology_electricity_details Product  \
0                    NaN                            NaN     NaN
1                    NaN                            NaN     NaN
2                    NaN                            NaN     NaN
3                    NaN                            NaN     NaN
4                    NaN                            NaN     NaN
5                    NaN                            NaN     NaN
6                    NaN                            NaN     NaN
7    Dedicated renewable                 Others/Various      H2
8    Dedicated renewable                 Others/Various      H2
9    Dedicated renewable                  Offshore wind      H2

   EndUse_Refining  EndUse_Ammonia  EndUse_Methanol  EndUse_Iron&Steel  \
0              NaN             NaN              NaN                NaN
1              NaN             NaN              NaN                NaN
2              NaN             NaN              NaN                NaN
3              NaN             NaN              NaN                NaN
4              NaN             NaN              NaN                NaN
5              NaN             NaN              NaN                NaN
6              NaN             NaN              NaN                NaN
7              NaN             NaN              NaN                NaN
8              NaN             NaN              NaN                NaN
9              1.0             NaN              NaN                NaN

   EndUse_Other Ind  EndUse_Mobility  EndUse_Power  EndUse_Grid inj.  \
0               NaN              NaN           NaN               NaN
1               NaN              NaN           NaN               NaN
2               NaN              NaN           NaN               NaN
3               NaN              NaN           NaN               NaN
4               NaN              NaN           NaN               NaN
5               NaN              NaN           NaN               NaN
6               NaN              NaN           NaN               NaN
7               NaN              1.0           NaN               NaN
8               NaN              1.0           NaN               NaN
9               1.0              NaN           NaN               NaN

   EndUse_CHP  EndUse_Domestic heat  EndUse_Biofuels  EndUse_Synfuels  \
0         NaN                   NaN              NaN              NaN
1         NaN                   NaN              NaN              NaN
2         NaN                   NaN              NaN              NaN
3         NaN                   NaN              NaN              NaN
4         NaN                   NaN              NaN              NaN
5         NaN                   NaN              NaN              NaN
6         NaN                   NaN              NaN              NaN
7         NaN                   NaN              NaN              NaN
8         NaN                   NaN              NaN              NaN
9         NaN                   NaN              NaN              NaN

   EndUse_CH4 grid inj.  EndUse_CH4 mobility Announced Size  Capacity_MWel  \
0                   NaN                  NaN   2756 kt H2/y            NaN
1                   NaN                  NaN    488 kt H2/y            NaN
2                   NaN                  NaN         17.4GW   17443.883124
3                   NaN                  NaN            7MW       6.541400
4                   NaN                  NaN        141.7MW     141.760154
5                   NaN                  NaN           78MW      78.393800
6                   NaN                  NaN           46MW      46.556344
7                   NaN                  NaN          2.5MW       2.500000
8                   NaN                  NaN           26MW      23.500000
9                   NaN                  NaN            4GW    4000.000000

   Capacity_Nm³ H₂/h  Capacity_kt H2/y  Capacity_t CO₂ captured/y  \
0       3.535952e+06       2756.769803                        NaN
1       6.255649e+05        487.715413                        NaN
2       3.876418e+06       3022.210898                        NaN
3       1.257962e+03          0.980757                        NaN
4       3.081742e+04         24.026497                        NaN
5                NaN               NaN                        NaN
6                NaN               NaN                        NaN
7       5.555556e+02          0.433133                        NaN
8       5.222222e+03          4.071453                        NaN
9       8.888889e+05        693.013333                        NaN

   IEA zero-carbon estimated normalized capacity [Nm³ H₂/hour]  \
0                                       0.000000e+00
1                                       0.000000e+00
2                                       3.876418e+06
3                                       1.257962e+03
4                                       3.081742e+04
5                                       0.000000e+00
6                                       0.000000e+00
7                                       5.555556e+02
8                                       5.222222e+03
9                                       8.888889e+05

        References   Latitude  Longitude    Technology_aggregate  LOWE_CF
0              NaN        NaN        NaN  Fossil fuels with CCUS      NaN
1              NaN        NaN        NaN                   Other      NaN
2              NaN        NaN        NaN            Electrolysis      NaN
3              NaN        NaN        NaN            Electrolysis      NaN
4              NaN        NaN        NaN            Electrolysis      NaN
5              NaN        NaN        NaN            Electrolysis      NaN
6              NaN        NaN        NaN            Electrolysis      NaN
7  [503][630][609]  51.703313   4.162536            Electrolysis     0.50
8  [503][630][609]  51.703313   4.162536            Electrolysis     0.50
9            [379]  53.465208   6.632985            Electrolysis     0.55

In [9]:
df = df.dropna(axis=0, subset=['Country'])  #deleting the lines without location information

df.shape

(2434, 35)

In [10]:
#look at the different answers per column and the amount of those to better understand how to analyse the columns data
cols = ['Project name', 'Country', 'Date online',
       'Decomission date', 'Status', 'Technology', 'Technology_details',
       'Technology_electricity', 'Technology_electricity_details', 'Product',
       'EndUse_Refining', 'EndUse_Ammonia', 'EndUse_Methanol',
       'EndUse_Iron&Steel', 'EndUse_Other Ind', 'EndUse_Mobility',
       'EndUse_Power', 'EndUse_Grid inj.', 'EndUse_CHP',
       'EndUse_Domestic heat', 'EndUse_Biofuels', 'EndUse_Synfuels',
       'EndUse_CH4 grid inj.', 'EndUse_CH4 mobility', 'Announced Size',
       'Capacity_MWel', 'Capacity_Nm³ H₂/h', 'Capacity_kt H2/y',
       'Capacity_t CO₂ captured/y',
       'IEA zero-carbon estimated normalized capacity [Nm³ H₂/hour]',
       'References', 'Latitude', 'Longitude', 'Technology_aggregate',
       'LOWE_CF']
for column in cols:
    print(len(df[column].unique()), "{}: ".format(column), df[column].unique())
    print("-----------------------------------------------")

2409 Project name:  ['H2GO Energy Park Oude-Tonge - 1st phase'
 'H2GO Energy Park Oude-Tonge - 2nd phase' 'NortH2, phase 1' ...
 'H2 hub Bintulu Sarawak ' "Nujio'qonik Green Hydrogen -phase 4"
 'Green Hydrogen Hub Stuttgart (GH2S)']
-----------------------------------------------
102 Country:  ['NLD' 'NOR' 'SWE' 'ESP' 'USA' 'JPN' 'CHE' 'DEU' 'GBR' 'DNK' 'AUT' 'CHN'
 'CAN' 'EST' 'FRA' 'MYS' 'AUS' 'POL' 'FIN' 'SGP' 'THA' 'ITA' 'CRI' 'CHL'
 'BEL' 'IND' 'GRC' 'ISL' 'TUR' 'ARG' 'IRN' 'NZL' 'PRT' 'LBN' 'MRT'
 'PRT\nESP' 'SAU' 'ROM\nDEU\nAUT' 'POL\nCZE\nSVK\nHUN' 'COK' 'ZAF' 'ARE'
 'OMN' 'URY' 'PRY' 'ESP\nFRA' 'KOR' 'MAR' 'ALB' 'IDN' 'BRB' 'TTO' 'BGD'
 'BRA' 'HUN' 'TWN' 'MEX' 'VNM' 'SVN' 'CZE' 'SVK' 'DEU\nDNK' 'LTU' 'LVA'
 'IRL' 'PER' 'RUS' 'COL' 'KAZ' 'EGY' 'ZWE' 'NAM' 'KEN' 'BWA' 'PAK' 'COD'
 'AGO' 'UKR' 'BGR' 'LUX' 'ROU' 'LKA' 'NER' 'DJI' 'UZB' 'PAN' 'MNG' 'DMA'
 'JOR' 'MOZ' 'DOM' 'QAT' 'SRB' 'PHL' 'FJI' 'UGA' 'CYP' 'HRV' 'TUN' 'DZA'
 'BHR' 'ISR']
-----------------------------------------------
46 Date online:  [2025. 2030. 2028. 2021. 2022. 2020. 2019. 2018. 2017. 2035. 2027. 2016.
   nan 2015. 2014. 2013. 2024. 2005. 2012. 2011. 2010. 2009. 2008. 2007.
 2006. 2004. 2003. 2001. 2000. 2023. 2029. 2026. 2002. 2040. 2032. 2031.
 1965. 2038. 1982. 1975. 2033. 1992. 2043. 2036. 2037. 2034.]
-----------------------------------------------
25 Decomission date:  [  nan 2023. 2022. 2021. 2020. 2017. 2018. 2015. 2012. 2013. 2014. 2011.
 2008. 2016. 2006. 2009. 2007. 2019. 2004. 2005. 2025. 2026. 2024. 2063.
 2028.]
-----------------------------------------------
8 Status:  ['FID/Construction' 'Concept' 'Feasibility study' 'Operational' 'DEMO'
 'Decommisioned' 'Other/Unknown' nan]
-----------------------------------------------
13 Technology:  ['Other Electrolysis' 'SOEC' 'ALK' 'PEM' 'NG w CCUS' 'Biomass'
 'Oil w CCUS' 'Other' 'Coal w CCUS' 'AEM' 'Biomass w CCUS'
 'Other electrolysis' nan]
-----------------------------------------------
47 Technology_details:  ['Unknown PtX' nan 'ATR+CCUS' 'SMR+CCUS' 'Coke gasification with CCUS'
 'Microbial fermentation' 'PEM+ALK+SOEC' 'PEM' 'Bitumen gasification+CCUS'
 'Biogas reforming' 'Biomass plasma-enhanced gasification'
 'Methane pyrolysis' 'Coal gasification with CCUS' 'Petroleum coke+CCUS'
 'Petcoke+biomass gasification with CCUS'
 'Heavy oil residue gasification+CCUS' 'Biomass gasification'
 'Combination of electrolysis and NG w CCUS' 'ALK+PEM' 'Various'
 'Unknown technology' 'GHR-ATR' 'PEM & SOEC' 'Waste gasification'
 'Unknown Technology' 'ME450' 'Allam Cycle'
 'Waste gases from biofuels production' 'Waste gasification CCUS'
 'Unknown green/blue hydrogen' 'Waste pyrolysis' 'Waste thermolysis'
 'Concentrated solar synfuels production' 'ATR'
 'Biomethanol steam reforming' 'Mix of natural gas and biogas'
 'Supercritical water gasification (SCW) plant'
 'Underground Partial Oxidation' 'NG w CCUS+Electrolysis'
 'BrightLoop technology' 'Hysata capillary design' 'Not defined'
 'Ethanol reforming' 'eREACT technology' 'CO2 convective reformer (CCR)'
 'ALK + PEM' 'E-TAC']
-----------------------------------------------
7 Technology_electricity:  ['Dedicated renewable' 'Grid' 'Other/unknown' 'Other/Unknown' nan
 'Grid+Renewables' 'Nuclear']
-----------------------------------------------
7 Technology_electricity_details:  ['Others/Various' 'Offshore wind' nan 'Solar PV' 'Hydropower'
 'Onshore wind' 'Unknown']
-----------------------------------------------
8 Product:  ['H2' 'Synfuels' 'Ammonia' 'MeOH' 'CH4' nan 'Various' 'LOHC']
-----------------------------------------------
2 EndUse_Refining:  [nan  1.]
-----------------------------------------------
2 EndUse_Ammonia:  [nan  1.]
-----------------------------------------------
2 EndUse_Methanol:  [nan  1.]
-----------------------------------------------
2 EndUse_Iron&Steel:  [nan  1.]
-----------------------------------------------
2 EndUse_Other Ind:  [nan  1.]
-----------------------------------------------
2 EndUse_Mobility:  [ 1. nan]
-----------------------------------------------
2 EndUse_Power:  [nan  1.]
-----------------------------------------------
2 EndUse_Grid inj.:  [nan  1.]
-----------------------------------------------
2 EndUse_CHP:  [nan  1.]
-----------------------------------------------
2 EndUse_Domestic heat:  [nan  1.]
-----------------------------------------------
2 EndUse_Biofuels:  [nan  1.]
-----------------------------------------------
2 EndUse_Synfuels:  [nan  1.]
-----------------------------------------------
2 EndUse_CH4 grid inj.:  [nan  1.]
-----------------------------------------------
2 EndUse_CH4 mobility:  [nan  1.]
-----------------------------------------------
1233 Announced Size:  ['2.5MW' '26MW' '4GW' ... '1Mt NH3/y production'
 '10 kgH2/d for 5Kg SAF/d, capacity' '2.600 GW']
-----------------------------------------------
705 Capacity_MWel:  [2.50000000e+00 2.35000000e+01 4.00000000e+03 5.02635832e+01
 4.50000000e+00 5.00000000e+02 2.00000000e+01 1.10000000e+02
 1.00000000e+00 1.00000000e+01 2.00000000e+00 1.30000000e+00
 1.12500000e+00 7.00000000e-01 2.50000000e-01            nan
 5.20000000e-03 6.00000000e+00 4.00000000e+00 7.28000000e-01
 5.00000000e-01 7.50000000e-01 3.50000000e-01 2.76000000e-01
 2.00000000e-01 1.50000000e-01 8.10000000e-02 2.50000000e-02
 1.00000000e-02 7.00000000e-03 6.00000000e-03 1.50000000e+00
 5.00000000e-02 4.50000000e-02 2.40000000e+00 8.00000000e-01
 6.00000000e-01 2.25000000e-01 1.92400000e-01 1.12500000e-01
 3.34400000e-02 3.80000000e-02 1.84000000e-02 1.12500000e-03
 1.15437894e+04 6.25000000e-02 4.68000000e-02 1.25000000e+00
 1.20000000e+02 1.85000000e-01 7.50000000e-02 1.04000000e-02
 3.00000000e-01 1.45600000e-01 2.00000000e-02 2.08000000e-02
 6.30000000e+00 4.30711610e-01 2.60000000e-01 1.80000000e-01
 4.00000000e-02 3.12000000e-03 5.00000000e+00 1.65000000e-01
 1.40000000e-01 1.20000000e-01 1.08000000e-01 1.00000000e-01
 3.00000000e-02 8.84000000e-03 1.24200000e-01 4.95000000e-02
 8.74000000e-02 6.50000000e-02 2.20000000e-01 8.28000000e-01
 1.60000000e-01 8.00000000e-02 5.00000000e-03 4.00000000e-03
 2.50000000e-03 4.60000000e-02 3.64000000e-02 3.64000000e-03
 4.68000000e-04 5.50000000e-02 2.04240000e+00 3.40000000e-02
 1.20000000e+00 1.38000000e-01 9.20000000e-02 1.14000000e-01
 5.52000000e-02 2.50000000e+03 1.29213483e+00 2.10000000e+02
 7.50000000e+01 2.50000000e+01 1.00000000e+02 6.44000000e-03
 8.32000000e-02 1.00000000e+03 2.64269015e+00 4.50000000e+01
 4.80000000e-02 2.40000000e+01 2.43800000e-02 3.70000000e-01
 1.50000000e-02 3.00000000e+00 2.40000000e+02 1.05000000e+03
 7.10000000e+00 6.70000000e+02 5.00000000e+01 6.50000000e+01
 3.00000000e+03 2.20000000e+03 2.60000000e+01 2.00000000e+03
 9.00000000e+02 3.50000000e+02 2.52808989e+02 2.50000000e+02
 4.00000000e+01 3.00000000e+01 1.60000000e+02 1.50000000e+02
 2.80000000e+02 9.50000000e+01 2.60000000e+00 6.85247775e+01
 1.50000000e+01 8.80000000e+00 2.66789800e+01 7.20000000e-02
 1.20000000e-03 3.40000000e+00 1.00000000e-03 3.12000000e-01
 1.10000000e-01 9.20000000e-03 1.56000000e-03 1.82000000e-01
 6.76000000e-02 1.35000000e-01 5.20000000e-01 4.10000000e-02
 3.27600000e-02 3.60000000e-03 3.40000000e-03 2.60000000e-03
 2.25000000e-04 9.90000000e-02 6.50000000e-03 4.60000000e+00
 9.26029963e+00 3.10000000e+00 3.50000000e+00 2.52808989e-02
 4.60000000e-03 1.47503976e+02 3.00000000e+02 1.40000000e+00
 2.00000000e+02 6.00000000e-02 1.60000000e+00 5.30000000e+01
 3.60000000e+02 4.13857678e+00 9.83787389e+00 1.75000000e-01
 3.10000000e+02 5.50000000e+01 4.86891386e-02 7.00000000e+02
 1.63000000e+00 6.70000000e-01 2.70000000e+01 2.88594736e+03
 2.37000000e+02 1.57000000e+02 1.80000000e+02 5.20000000e-02
 9.00000000e+01 6.00000000e+03 2.80000000e+01 2.85000000e+03
 4.00000000e-01 4.61751578e-01 6.49338156e+02 7.20000000e+00
 7.00000000e+00 5.77189472e+00 4.00000000e+02 8.00000000e+02
 1.46067416e-02 1.25000000e-01 7.00000000e+01 4.12278194e+02
 4.50000000e-04 2.25000000e+02 1.45649831e+00 1.60000000e+01
 1.40000000e+02 3.46313683e+03 3.89513109e+00 8.39000000e+02
 6.81647940e+00 2.25000000e-01 2.10674157e+01 4.50000000e-01
 1.89796538e+03 7.80000000e+01 2.32817087e+02 2.30000000e+01
 8.40000000e+01 2.48000000e+02 2.93468780e+00 2.73876404e+03
 2.87265918e+00 5.30337079e+00 4.86891386e+01 4.12690473e+02
 4.32000000e-01 9.00000000e-01 9.00000000e+00 8.00000000e+03
 4.24326507e+01 1.73156842e+03 2.73876404e+02 6.40000000e+02
 5.90015905e+01 2.60000000e+02 1.80000000e+01 1.23952921e+02
 4.21348315e+00 8.83453274e+01 7.50000000e+00 4.30000000e-01
 5.40000000e+01 6.00000000e+01 2.10000000e+03 4.21348315e-01
 2.10000000e+00 1.70000000e+01 2.00000000e+04 9.33300000e+03
 5.00000000e+03 2.65000000e+03 3.50000000e+01 6.90000000e+01
 5.84349486e+02 1.00604125e+03 1.21600000e+03 1.82584270e+02
 3.75000000e+00 3.24000000e+00 1.44000000e+00 4.15742717e+04
 8.00000000e+01 4.21348315e-02 2.72000000e+02 1.40000000e+01
 1.05000000e+01 4.86891386e-03 3.17454210e+00 4.05742821e+02
 4.30000000e+00 1.00046175e-01 3.00138525e-01 9.33764301e-01
 9.10000000e+01 6.89206984e+02 5.50000000e+00 8.69524396e+02
 6.00000000e+02 2.38379252e+00 1.65000000e+03 5.16853933e+01
 2.75000000e+03 3.30000000e+02 6.32022472e+01 1.49000000e+02
 4.20000000e+02 1.04943540e+03 1.40000000e+03 1.30000000e+04
 3.72500000e+02 1.11750000e+03 5.37000000e+00 3.25587334e+01
 5.60000000e+01 3.60000000e+03 1.36000000e+03 2.88594736e+01
 1.15437894e+02 9.48033708e-01 6.34908419e+02 5.16000000e+01
 3.40000000e+02 3.03913977e+02 2.30875789e+03 2.07871358e+03
 8.50000000e+01 3.55000000e+02 1.50000000e+03 7.60000000e+03
 1.07500000e+03 5.40465532e+02 2.16186213e+03 8.89504323e+01
 1.48250721e+04 1.20000000e+01 5.05040788e+01 8.18493343e+02
 6.34983598e+02 2.02016315e+00 7.16292135e+02 2.26000000e+02
 4.30000000e+01 2.20863860e+02 3.96000000e+02 5.77189472e+02
 1.66297060e+03 3.57857473e+03 3.03492135e+03 5.00230876e+01
 1.12000000e+03 9.81222103e+02 4.90611051e+02 3.24936295e+02
 1.97500000e+03 5.90000000e+02 2.12520000e+02 5.40000000e+02
 1.44297368e+02 1.92396491e+04 3.30000000e+03 4.10000000e+03
 3.01581499e+02 2.88594736e+02 3.20000000e+02 3.18000000e+03
 2.20000000e-02 4.60000000e+01 9.20000000e+01 0.00000000e+00
 1.05000000e+02 1.75000000e+01 2.96501441e+02 1.29867631e+00
 3.20000000e+01 9.99000000e+02 4.32892104e+02 3.40000000e+01
 5.19470525e+02 2.20000000e+02 3.65168539e+01 1.93740228e+02
 3.80625977e+03 5.28020805e+02 7.74922543e+02 6.66974501e+00
 2.52000000e+00 1.20000000e+03 2.90000000e+02 1.29000000e+01
 5.40000000e+01 1.21209789e+01 2.42191781e+00 2.90392694e+01
 2.07000000e+02 2.87123018e+02 1.33895131e+02 2.37201153e+02
 2.43445693e+00 2.30875789e+02 2.07788210e+03 2.07871358e+02
 4.50000000e+02 1.48250721e+01 1.53157226e+04 2.48191473e+02
 5.38710174e+01 1.73156842e+02 1.35000000e+02 2.10674157e+00
 4.40000000e+02 1.04943540e+04 1.30000000e+03 1.80000000e+03
 7.60000000e+00 1.10431930e+02 4.74402306e+01 4.69658283e+03
 4.19774162e+03 6.29661242e+03 1.21500000e+03 1.48914884e+02
 5.62297984e+03 4.26785883e+02 3.15000000e+02 3.20000000e+00
 9.00415576e-01 3.48000000e-01 8.42696629e-03 1.75000000e+00
 2.89107793e+01 4.90000000e+01 1.58239700e+01 8.52059925e+00
 2.13548853e+01 2.07788210e+02 1.24672926e+02 6.79970310e+02
 1.07357242e+02 3.14279668e+01 1.22882612e+02 9.12164589e+01
 1.61613052e+02 1.48337694e+02 4.24811451e+00 3.20000000e+03
 2.40000000e+03 3.74168445e+03 3.35815572e+02 1.29919599e+03
 2.59839198e+02 3.34737828e+02 4.21415620e+02 8.08065261e+01
 1.54991802e+03 1.40000000e+04 5.40000000e+03 2.55219835e+03
 9.73782772e+02 3.60000000e+01 2.40000000e-01 3.49847496e+00
 7.00000000e+03 1.80000000e+00 3.62301832e+03 1.45000000e+02
 8.00000000e+00 2.98000000e+03 2.53963368e+03 2.74000000e+02
 4.67523472e+03 1.15000000e+02 3.63774877e+03 1.58218665e+02
 2.26566107e+00 5.77189472e+01 1.09666000e+02 1.66297087e+03
 2.10674157e+02 3.86235955e+02 6.92904528e+02 2.21255964e+01
 2.49445630e+03 1.70000000e+02 5.60000000e+02 9.60000000e+03
 6.66974501e+02 6.50000000e+02 1.38525473e+02 8.40000000e+02
 3.87480457e+02 8.19811573e+02 6.75000000e+02 1.90000000e+02
 2.07871358e+03 3.61235114e+02 3.10236454e+00 3.80945052e+01
 2.36122966e+03 1.54604702e+02 1.25000000e+02 5.05040788e+02
 8.73059706e+02 4.04032630e+02 5.19678396e+03 1.71000000e+02
 1.64499000e+02 1.59021589e+03 1.63344621e+03 8.17877482e+03
 1.03894105e+01 3.11807038e+02 1.89606742e+02 4.30684527e+02
 2.45000000e+01 1.06000000e+01 5.20000000e+00 3.46452264e+02
 1.33394900e+04 8.33084501e-01 1.50000000e+04 2.53963368e+04
 1.03935679e+02 3.50000000e+03 4.75000000e+00 4.15250000e+02
 4.24750000e+02 7.10000000e+02 6.10000000e+02 1.26404494e+00
 1.29867631e+01 1.81887439e+03 2.30000000e+00 1.25163000e+02
 1.10638320e+03 1.21702360e+03 9.23503155e-01 9.02889246e+02
 1.94879399e+03 2.55384812e+02 1.00471157e+03 2.30000000e+03
 3.03783933e+01 2.00092350e+00 2.12405726e-01 1.44297368e-01
 6.60000000e+00 3.40000000e-01 1.27500000e+03 1.09550562e+00
 3.73149531e+01 8.42696629e-02 1.49261197e+03 3.44000000e+03
 2.23949515e-01 8.65784208e-01 4.38663999e+01 2.21762271e+02
 1.89664461e-01 7.39033400e-01 7.30337079e+03 5.38864091e-01
 3.03370787e+01 1.15437894e-01 3.69603785e+01 8.28587553e-03
 1.58878997e+01 8.31152840e+00 4.61751578e+01 3.00138525e+02
 1.30000000e+02 2.70000000e+02 3.09209404e+02 2.18811956e+03
 1.15437894e+03 2.55000000e+02 1.03935679e+03 5.07926735e+02
 3.52000000e+02 8.42696629e+03 1.00000000e+04 2.07871325e+04
 9.48413073e+02 1.15437894e-02 4.61751578e-02 5.77189472e-03
 9.21699438e+01 1.25000000e+04 7.21486840e+02 2.33855278e+02
 3.27397390e+02 4.03241960e+02 5.50000000e+02 1.61613052e+04
 2.94366631e-01 2.76468907e+02 1.55903519e+01 9.00415576e+01
 8.65784208e+00 5.52159651e+02 5.06000000e+00 6.23614075e+02
 3.31295790e+02 3.50000000e+04 6.62591581e+02 4.30711610e+00
 6.92627366e+01 8.08491782e+02 5.64429865e+01 1.10431930e+01
 5.52159651e+01 4.10958904e-03 1.23344600e+00 1.29919599e+02
 9.35421113e+02 1.55903519e+02 1.87084223e+02 3.46313683e+02
 1.35400000e+00 2.90610342e+02 3.87480457e+01 6.95721160e+01
 2.20863860e+03 8.61888083e+01 9.68701141e+02 5.81220685e+02
 6.81953315e+01 2.96501441e+01 9.46590734e+02 1.48250721e+02
 5.93002882e-01 1.92725937e+02 5.93002882e+01 4.15102018e+01
 2.19411066e+01 3.12106780e+00 3.07834385e+01 7.69585963e+00
 8.19091493e+00 7.51368174e+02 5.85762539e+02 6.40000000e+01
 1.10000000e+01 6.34908419e+01 6.37472166e+02 6.75000000e-02
 2.40495613e+01 4.43524542e+02 3.63000000e+02 3.16011236e+00
 7.41253603e+02 1.48250721e+03 1.53917193e+03 1.15274117e+03
 4.43524542e+03 4.41727720e+02 3.31295790e+01 2.20863860e+01
 8.39548323e+02 1.31287174e+03 8.08065261e+02 6.92627366e+02
 9.10674523e-01 3.94625627e+00 5.19678396e+02 9.18000000e+00
 1.82343297e+02 1.00392664e+03 1.44000000e+03 1.37000000e+02
 5.41116458e+02 7.73023511e+02 3.72707764e+02 4.96943686e+03
 4.83691854e+00 5.47029891e+02 2.55681771e+03 7.21486840e-01
 2.88594736e+00 5.77189472e-01 6.92627366e+03 2.27000000e+02
 4.15742717e+02 2.98295399e+02 4.40000000e+01 2.04224493e+02
 2.18264926e+02 1.01261311e+02 2.31907053e+02 4.96943686e+02
 1.98777474e+02 1.32518316e+02 5.52159651e+03 4.19641334e+02
 1.10431930e+03 1.76691088e+02 3.61112411e+02 8.83455441e+02
 1.65647895e+02 7.54386640e+02 1.73156842e-02 2.42419578e+02
 1.56225950e+01 1.44297368e+03 5.94974022e+02 2.94137972e+02
 2.95177329e+02 3.11682315e+02 2.59839198e+03 9.10476550e+02
 1.84700631e+03 2.88284736e+03 5.20000000e+02 8.50000000e+03
 3.70000000e+03 3.90000000e+03 1.30000000e+01 9.30000000e+00
 1.72000000e+01 4.70000000e+02 5.30000000e+02 3.96341390e+02
 9.10000000e+00 5.70000000e+00 4.10362618e+01 1.72144229e+03
 2.10674157e-02]
-----------------------------------------------
942 Capacity_Nm³ H₂/h:  [5.55555556e+02 5.22222222e+03 8.88888889e+05 1.32272587e+04
 9.78260870e+02 1.08695652e+05 3.84615385e+03 4.80769231e+02
 2.44444444e+04 1.92307692e+02 2.17391304e+03 3.84615385e+02
 4.34782609e+02 2.50000000e+02 2.16346154e+02 2.82608696e+02
 2.00000000e+02 5.00000000e+01            nan 1.00000000e+00
 1.15384615e+03 7.69230769e+02 2.17391304e+02 1.40000000e+02
 1.08695652e+02 9.61538462e+01 1.44230769e+02 6.73076923e+01
 6.00000000e+01 5.55555556e+01 3.84615385e+01 2.88461538e+01
 1.80000000e+01 4.80769231e+00 2.63157895e+00 1.34615385e+00
 1.57894737e+00 2.88461538e+02 1.11111111e+01 1.00000000e+01
 4.61538462e+02 1.53846154e+02 1.52173913e+02 1.30434783e+02
 1.34615385e+02 4.32692308e+01 3.70000000e+01 2.50000000e+01
 9.61538462e+00 8.80000000e+00 4.00000000e+00 2.50000000e-01
 3.89073034e+06 1.15437894e+05 2.56528654e+06 1.35869565e+01
 9.00000000e+00 2.40384615e+02 2.30769231e+04 3.55769231e+01
 1.44230769e+01 1.31578947e+01 2.00000000e+00 6.52173913e+01
 2.80000000e+01 3.84615385e+00 3.26086957e+02 1.36956522e+03
 9.36329588e+01 4.34782609e+03 4.34782609e+01 3.46153846e+01
 7.69230769e+00 6.00000000e-01 1.92307692e+03 9.61538462e+02
 3.58695652e+01 3.04347826e+01 2.60869565e+01 2.40000000e+01
 2.22222222e+01 6.52173913e+00 1.70000000e+00 1.33333333e+03
 2.70000000e+01 1.10000000e+01 1.92307692e+00 1.90000000e+01
 1.41304348e+01 4.88888889e+01 1.80000000e+02 4.44444444e+01
 3.47826087e+01 1.73913043e+01 1.30434783e+00 9.61538462e-01
 7.69230769e-01 4.80769231e-01 7.00000000e+00 7.00000000e-01
 9.00000000e-02 1.19565217e+01 1.52173913e+00 1.11111111e+00
 4.44000000e+02 7.39130435e+00 2.60869565e+02 2.66666667e+01
 3.00000000e+01 2.00000000e+01 1.08695652e+00 2.47826087e+01
 1.20000000e+01 1.08695652e+01 4.73684211e+01 5.43478261e+00
 5.55555556e+05 2.80898876e+02 4.24719101e+04 1.66666667e+04
 5.55555556e+03 2.22222222e+03 2.22222222e+04 4.80769231e+01
 1.05263158e+01 1.40000000e+00 5.43478261e+01 1.60000000e+01
 2.22222222e+05 5.87264477e+02 9.78260870e+03 1.04347826e+01
 6.40449438e+04 4.61538462e+03 1.92307692e+04 5.30000000e+00
 8.22222222e+01 3.26086957e+00 5.76923077e+02 1.92134831e+05
 5.33333333e+04 2.33333333e+05 1.36538462e+03 1.45652174e+05
 9.61538462e+03 2.22222222e+02 1.44444444e+04 5.76923077e+05
 4.78260870e+05 5.77777778e+03 4.44444444e+05 2.00000000e+05
 7.77777778e+04 5.61797753e+04 5.55555556e+04 8.88888889e+03
 6.52173913e+03 3.55555556e+04 3.33333333e+04 6.22222222e+04
 6.66666667e+03 2.11111111e+04 1.63043478e+02 5.65217391e+02
 1.31778418e+04 3.33333333e+03 1.69230769e+03 5.13057309e+03
 1.11111111e+03 2.60869565e-01 7.55555556e+02 2.17391304e-01
 6.57894737e+02 6.78260870e+01 2.11538462e+01 5.43478261e-01
 5.76923077e+01 3.00000000e-01 1.92307692e+01 3.50000000e+01
 1.30000000e+01 3.94736842e+00 3.94736842e+01 2.93478261e+01
 1.00000000e+02 7.88461538e+00 6.30000000e+00 7.82608696e-01
 7.39130435e-01 5.00000000e-01 1.92307692e-01 5.00000000e-02
 2.15217391e+01 8.69565217e+00 1.41304348e+00 1.00000000e+03
 4.44444444e+02 1.51000000e+05 5.00000000e+04 3.15789474e+01
 2.88888889e+02 1.30434783e+03 1.79570058e+05 2.01310861e+03
 6.73913043e+02 7.60869565e+02 1.15384615e+02 8.69565217e+02
 4.44444444e+00 4.23076923e+01 5.61797753e+00 1.11111111e+05
 3.20660818e+04 1.11111111e+04 6.66666667e+04 3.04347826e+02
 4.68164794e+03 4.34782609e+04 1.30434783e+01 4.44444444e+04
 3.07692308e+02 1.01923077e+04 5.61797753e+03 6.41321636e+03
 6.35162383e+04 8.00000000e+04 7.95880150e+02 1.89189883e+03
 6.57894737e+01 2.63157895e+02 3.60486891e+05 1.28264327e+05
 3.36538462e+01 1.28264327e+02 6.73913043e+04 3.84615385e+04
 1.19565217e+04 8.69565217e+03 6.52173913e+04 1.57303371e+05
 2.17391304e+04 3.33333333e+00 5.61797753e+02 2.34082397e+02
 8.88888889e+02 9.36329588e+00 1.55555556e+05 3.62222222e+02
 5.76923077e+03 1.28846154e+02 6.00000000e+03 6.41321636e+05
 5.26666667e+04 1.08695652e+03 3.01923077e+04 4.44444444e+03
 4.00000000e+04 1.73076923e+04 1.63043478e+04 1.33333333e+06
 6.22222222e+03 6.33333333e+05 7.69230769e+01 1.02611462e+02
 4.48925145e+02 1.44297368e+05 1.60000000e+03 1.55555556e+03
 1.03894105e+06 1.28264327e+03 8.88888889e+04 1.73913043e+05
 5.43478261e+02 3.20660818e+05 4.80769231e+03 2.80898876e+00
 3.28947368e+01 1.55555556e+04 3.88888889e+01 9.16173765e+04

In [11]:
mask = (df.loc[:, 'Status'] != 'Concept') & (df.loc[:, 'Status'] != 'Feasibility study') & (df.loc[:, 'Status'] != 'Decommisioned')
df_real = df.loc[mask, :]
df_real

,Project name,Country,Date online,Decomission date,Status,Technology,Technology_details,Technology_electricity,Technology_electricity_details,Product,...,Capacity_MWel,Capacity_Nm³ H₂/h,Capacity_kt H2/y,Capacity_t CO₂ captured/y,IEA zero-carbon estimated normalized capacity [Nm³ H₂/hour],References,Latitude,Longitude,Technology_aggregate,LOWE_CF
7,H2GO Energy Park Oude-Tonge - 1st phase,NLD,2025.0,NaN,FID/Construction,Other Electrolysis,Unknown PtX,Dedicated renewable,Others/Various,H2,...,2.500000,555.555556,0.433133,NaN,555.555556,[503][630][609],51.703313,4.162536,Electrolysis,0.50
10,Norsk e-Fuel Phase 1,NOR,2028.0,NaN,FID/Construction,SOEC,NaN,Dedicated renewable,Others/Various,Synfuels,...,50.263583,13227.258735,10.312500,NaN,13227.258735,[414] [521][1288][1449] [1693],65.840500,13.195267,Electrolysis,0.50
12,HYBRIT pilot,SWE,2021.0,NaN,Operational,ALK,NaN,Grid,NaN,H2,...,4.500000,978.260870,0.762691,NaN,978.260870,[299] [340] [434] [576] [2224],65.585456,22.157661,Electrolysis,0.57
13,HYBRIT demo,SWE,2025.0,NaN,FID/Construction,ALK,NaN,Grid,NaN,H2,...,500.000000,108695.652174,84.743478,NaN,108695.652174,[299] [340][1108],65.585456,22.157661,Electrolysis,0.57
14,Iberdrola - Puertollano I,ESP,2022.0,NaN,Operational,PEM,NaN,Dedicated renewable,Solar PV,Ammonia,...,20.000000,3846.153846,2.998615,NaN,3846.153846,[567] [572][620][631],38.672067,-4.053051,Electrolysis,0.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2397,Rorvik hydrogen hub,NOR,2027.0,NaN,FID/Construction,Other Electrolysis,Unknown PtX,Other/Unknown,NaN,H2,...,20.000000,4444.444444,3.465067,NaN,4444.444444,NaN,64.888375,11.300169,Electrolysis,0.57
2411,Hydro Havrand - Hoyanger,NOR,2025.0,NaN,FID/Construction,PEM,NaN,Dedicated renewable,Hydropower,H2,...,5.000000,961.538462,0.749654,NaN,961.538462,[2714],61.220253,6.075355,Electrolysis,0.80
2431,E-methane pilot project,OMN,NaN,NaN,DEMO,Other Electrolysis,Unknown PtX,Other/Unknown,NaN,CH4,...,41.036262,9119.169296,7.109669,NaN,9119.169296,[2736],23.227352,56.780536,Electrolysis,0.57
2437,IHI - ISCE2 SAF project,SGP,2025.0,NaN,DEMO,Other Electrolysis,Unknown PtX,Other/unknown,NaN,Synfuels,...,0.021067,4.681648,0.003650,NaN,4.681648,[2743],1.278304,103.785885,Electrolysis,0.57
2440,Green Hydrogen Hub Stuttgart (GH2S),DEU,2026.0,NaN,FID/Construction,Other Electrolysis,Unknown PtX,Other/Unknown,NaN,H2,...,10.000000,2222.222222,1.732533,NaN,2222.222222,[2746],48.798544,9.146299,Electrolysis,0.57

In [12]:
df_real["Date online"].unique()

array([2025., 2028., 2021., 2022., 2020., 2019., 2018., 2017., 2016.,
       2015., 2014., 2013., 2024., 2005., 2012., 2011., 2010., 2009.,
       2008., 2007., 2006., 2004., 2003., 2001., 2000., 2023., 2026.,
         nan, 2002., 2027., 2030., 1965., 1982., 1992., 2029.])

In [13]:
pd.crosstab(columns=df_real.loc[:, "Date online"], index="count")

Date online,1965.0,1982.0,1992.0,2000.0,2001.0,2002.0,2003.0,2004.0,2005.0,2006.0,...,2021.0,2022.0,2023.0,2024.0,2025.0,2026.0,2027.0,2028.0,2029.0,2030.0
row_0,,,,,,,,,,,,,,,,,,,,,
count,1,1,1,10,2,1,7,6,5,7,...,47,49,78,146,101,62,18,12,2,4

In [14]:
mask = (df.loc[:, 'Technology'] != 'Oil w CCUS') & (df.loc[:, 'Technology'] != 'NG w CCUS') & (df.loc[:, 'Technology'] != 'Coal w CCUS')
df_techn = df.loc[mask, :]
df_techn

,Project name,Country,Date online,Decomission date,Status,Technology,Technology_details,Technology_electricity,Technology_electricity_details,Product,...,Capacity_MWel,Capacity_Nm³ H₂/h,Capacity_kt H2/y,Capacity_t CO₂ captured/y,IEA zero-carbon estimated normalized capacity [Nm³ H₂/hour],References,Latitude,Longitude,Technology_aggregate,LOWE_CF
7,H2GO Energy Park Oude-Tonge - 1st phase,NLD,2025.0,NaN,FID/Construction,Other Electrolysis,Unknown PtX,Dedicated renewable,Others/Various,H2,...,2.500000,555.555556,0.433133,NaN,555.555556,[503][630][609],51.703313,4.162536,Electrolysis,0.50
8,H2GO Energy Park Oude-Tonge - 2nd phase,NLD,2030.0,NaN,Concept,Other Electrolysis,Unknown PtX,Dedicated renewable,Others/Various,H2,...,23.500000,5222.222222,4.071453,NaN,5222.222222,[503][630][609],51.703313,4.162536,Electrolysis,0.50
9,"NortH2, phase 1",NLD,2030.0,NaN,Feasibility study,Other Electrolysis,Unknown PtX,Dedicated renewable,Offshore wind,H2,...,4000.000000,888888.888889,693.013333,NaN,888888.888889,[379],53.465208,6.632985,Electrolysis,0.55
10,Norsk e-Fuel Phase 1,NOR,2028.0,NaN,FID/Construction,SOEC,NaN,Dedicated renewable,Others/Various,Synfuels,...,50.263583,13227.258735,10.312500,NaN,13227.258735,[414] [521][1288][1449] [1693],65.840500,13.195267,Electrolysis,0.50
11,Norsk e-Fuel Phase 2,NOR,2028.0,NaN,Feasibility study,SOEC,NaN,Dedicated renewable,Others/Various,Synfuels,...,50.263583,13227.258735,10.312500,NaN,13227.258735,[414] [521][1288],65.840500,13.195267,Electrolysis,0.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2434,Welspun ammonia project,IND,2029.0,NaN,Concept,Other Electrolysis,Unknown PtX,Other/Unknown,NaN,H2,...,1721.442285,382542.730023,298.245614,NaN,382542.730023,[2739],23.606543,69.805089,Electrolysis,0.57
2437,IHI - ISCE2 SAF project,SGP,2025.0,NaN,DEMO,Other Electrolysis,Unknown PtX,Other/unknown,NaN,Synfuels,...,0.021067,4.681648,0.003650,NaN,4.681648,[2743],1.278304,103.785885,Electrolysis,0.57
2438,H2 hub Bintulu Sarawak,MYS,NaN,NaN,Concept,Other Electrolysis,Unknown PtX,Other/Unknown,NaN,Ammonia,...,NaN,NaN,NaN,NaN,0.000000,[2744],3.167729,113.003280,Electrolysis,0.57
2439,Nujio'qonik Green Hydrogen -phase 4,CAN,2030.0,NaN,Concept,Other Electrolysis,Unknown PtX,Dedicated renewable,Onshore wind,H2,...,650.000000,144444.444444,112.614667,NaN,109024.678057,Data from World Energy GH2,48.522396,-58.434725,Electrolysis,0.40
2440,Green Hydrogen Hub Stuttgart (GH2S),DEU,2026.0,NaN,FID/Construction,Other Electrolysis,Unknown PtX,Other/Unknown,NaN,H2,...,10.000000,2222.222222,1.732533,NaN,2222.222222,[2746],48.798544,9.146299,Electrolysis,0.57

In [15]:
df_real_techn = df_real.loc[mask, :]
df_real_techn

,Project name,Country,Date online,Decomission date,Status,Technology,Technology_details,Technology_electricity,Technology_electricity_details,Product,...,Capacity_MWel,Capacity_Nm³ H₂/h,Capacity_kt H2/y,Capacity_t CO₂ captured/y,IEA zero-carbon estimated normalized capacity [Nm³ H₂/hour],References,Latitude,Longitude,Technology_aggregate,LOWE_CF
7,H2GO Energy Park Oude-Tonge - 1st phase,NLD,2025.0,NaN,FID/Construction,Other Electrolysis,Unknown PtX,Dedicated renewable,Others/Various,H2,...,2.500000,555.555556,0.433133,NaN,555.555556,[503][630][609],51.703313,4.162536,Electrolysis,0.50
10,Norsk e-Fuel Phase 1,NOR,2028.0,NaN,FID/Construction,SOEC,NaN,Dedicated renewable,Others/Various,Synfuels,...,50.263583,13227.258735,10.312500,NaN,13227.258735,[414] [521][1288][1449] [1693],65.840500,13.195267,Electrolysis,0.50
12,HYBRIT pilot,SWE,2021.0,NaN,Operational,ALK,NaN,Grid,NaN,H2,...,4.500000,978.260870,0.762691,NaN,978.260870,[299] [340] [434] [576] [2224],65.585456,22.157661,Electrolysis,0.57
13,HYBRIT demo,SWE,2025.0,NaN,FID/Construction,ALK,NaN,Grid,NaN,H2,...,500.000000,108695.652174,84.743478,NaN,108695.652174,[299] [340][1108],65.585456,22.157661,Electrolysis,0.57
14,Iberdrola - Puertollano I,ESP,2022.0,NaN,Operational,PEM,NaN,Dedicated renewable,Solar PV,Ammonia,...,20.000000,3846.153846,2.998615,NaN,3846.153846,[567] [572][620][631],38.672067,-4.053051,Electrolysis,0.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2397,Rorvik hydrogen hub,NOR,2027.0,NaN,FID/Construction,Other Electrolysis,Unknown PtX,Other/Unknown,NaN,H2,...,20.000000,4444.444444,3.465067,NaN,4444.444444,NaN,64.888375,11.300169,Electrolysis,0.57
2411,Hydro Havrand - Hoyanger,NOR,2025.0,NaN,FID/Construction,PEM,NaN,Dedicated renewable,Hydropower,H2,...,5.000000,961.538462,0.749654,NaN,961.538462,[2714],61.220253,6.075355,Electrolysis,0.80
2431,E-methane pilot project,OMN,NaN,NaN,DEMO,Other Electrolysis,Unknown PtX,Other/Unknown,NaN,CH4,...,41.036262,9119.169296,7.109669,NaN,9119.169296,[2736],23.227352,56.780536,Electrolysis,0.57
2437,IHI - ISCE2 SAF project,SGP,2025.0,NaN,DEMO,Other Electrolysis,Unknown PtX,Other/unknown,NaN,Synfuels,...,0.021067,4.681648,0.003650,NaN,4.681648,[2743],1.278304,103.785885,Electrolysis,0.57
2440,Green Hydrogen Hub Stuttgart (GH2S),DEU,2026.0,NaN,FID/Construction,Other Electrolysis,Unknown PtX,Other/Unknown,NaN,H2,...,10.000000,2222.222222,1.732533,NaN,2222.222222,[2746],48.798544,9.146299,Electrolysis,0.57